**Objetivos da aula:**
1. Compreender os fundamentos do NumPy e sua importância no ecossistema Python
2. Dominar a criação e manipulação de arrays multidimensionais
3. Aprender operações matemáticas e de álgebra linear com NumPy
4. Aplicar técnicas de broadcasting e indexação avançada
5. Integrar NumPy com outras bibliotecas científicas

**Carga horária estimada:** 4 horas (teoria + prática)

**Pré-requisitos:**
- Python intermediário (listas, dicionários, funções)
- Noções básicas de álgebra linear
- Acesso ao Google Colab

## 1. Introdução Teórica ao NumPy

### 1.1 O que é NumPy?
NumPy (Numerical Python) é a biblioteca fundamental para computação científica em Python. Fornece:

- Objeto **ndarray** multidimensional eficiente
- Funções matemáticas otimizadas
- Operações de álgebra linear, transformada de Fourier e números aleatórios
- Integração com código C/C++/Fortran

### 1.2 Por que usar NumPy?

**Vantagens sobre listas Python:**
- Velocidade: Operações vetorizadas (implementadas em C)
- Menos memória: Armazena dados de forma contígua
- Sintaxe concisa: Operações complexas com poucas linhas
- Base para outras bibliotecas (Pandas, SciPy, scikit-learn)

### 1.3 Arquitetura do NumPy

Principais componentes:
- **ndarray**: Estrutura de dados multidimensional
- **Ufuncs**: Funções universais para operações vetorizadas
- **DTypes**: Sistema de tipos numéricos flexível
- **Broadcasting**: Regras para operações entre arrays de diferentes shapes

### 1.4 NumPy vs Listas Python
Para entender por que o NumPy é mais eficiente que listas tradicionais, vejamos um exemplo de soma de elementos:

#### Com listas Python:
```python
lista = [1, 2, 3, 4, 5]
resultado = [x + 10 for x in lista]
print(resultado)  # Saída: [11, 12, 13, 14, 15]
```

#### Com NumPy:
```python
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
resultado = arr + 10
print(resultado)  # Saída: [11 12 13 14 15]
```
O NumPy executa a operação diretamente em todos os elementos do array, sem precisar de laços explícitos, tornando a execução mais rápida e eficiente.

## 2. Configuração Inicial e Primeiros Passos

### Instalando e Importando o NumPy
Para garantir que o NumPy está instalado, utilize:
```python
!pip install numpy
```
Depois, importe a biblioteca com:
```python
import numpy as np
```

### 2.1 Como instalar o NumPy
Se você estiver usando um ambiente local, instale o NumPy com:
```python
!pip install numpy
```
Se estiver no Google Colab, ele já vem pré-instalado.

### 2.2 Importando o NumPy
```python
import numpy as np
print(np.__version__)  # Verifica a versão instalada
```

In [1]:
import numpy as np
import matplotlib.pyplot as plt
from timeit import timeit

# Verificando a versão
print(f"NumPy versão: {np.__version__}")

NumPy versão: 1.26.4


## 3. Criando Arrays NumPy

### 3.1 Métodos Básicos de Criação

### Exemplos de Criação de Arrays
Criando um array unidimensional:
```python
arr1 = np.array([1, 2, 3, 4, 5])
print(arr1)
```
Criando uma matriz 2D:
```python
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
print(arr2)
```

### 3.1 Criando Arrays a partir de Listas
```python
arr1 = np.array([10, 20, 30, 40])
print("Array 1D:", arr1)
```

### 3.2 Criando Matrizes
```python
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
print("Array 2D:")
print(arr2)
```

### 3.3 Criando Arrays com Zeros e Uns
```python
zeros = np.zeros((2, 3))  # Matriz 2x3 preenchida com zeros
ones = np.ones((3, 3))   # Matriz 3x3 preenchida com uns
print("Matriz de zeros:")
print(zeros)
print("Matriz de uns:")
print(ones)
```

In [2]:
# A partir de listas Python
arr1 = np.array([1, 2, 3, 4, 5])
print("1D array:", arr1)

# Array 2D
arr2d = np.array([[1, 2, 3], [4, 5, 6]])
print("\n2D array:\n", arr2d)

# Arrays especiais
zeros = np.zeros((3, 4))
ones = np.ones((2, 2, 2))
identity = np.eye(3)
range_arr = np.arange(0, 20, 2)  # Similar ao range() mas retorna array
random_arr = np.random.rand(5)  # Valores uniformes entre [0, 1)

print("\nZeros:\n", zeros)
print("\nOnes 3D:\n", ones)
print("\nMatriz identidade:\n", identity)
print("\nArray com arange:\n", range_arr)
print("\nArray aleatório:\n", random_arr)

1D array: [1 2 3 4 5]

2D array:
 [[1 2 3]
 [4 5 6]]

Zeros:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

Ones 3D:
 [[[1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]]]

Matriz identidade:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

Array com arange:
 [ 0  2  4  6  8 10 12 14 16 18]

Array aleatório:
 [0.47116388 0.81041644 0.03184975 0.5059475  0.43344824]


3.2 Atributos Fundamentais de um Array

Todo array NumPy possui:
- **shape**: Dimensões do array (tupla)
- **ndim**: Número de dimensões
- **size**: Número total de elementos
- **dtype**: Tipo dos dados
- **itemsize**: Tamanho em bytes de cada elemento
- **nbytes**: Tamanho total em bytes (size * itemsize)

In [3]:
# Exemplo de inspeção de atributos
arr = np.random.rand(3, 4, 2)

print("Array:\n", arr)
print("\nShape:", arr.shape)
print("Número de dimensões:", arr.ndim)
print("Número total de elementos:", arr.size)
print("Tipo dos dados:", arr.dtype)
print("Tamanho de cada elemento (bytes):", arr.itemsize)
print("Tamanho total (bytes):", arr.nbytes)

Array:
 [[[0.13675097 0.8815968 ]
  [0.96841977 0.04147224]
  [0.12369418 0.02252748]
  [0.96647289 0.35939754]]

 [[0.98463281 0.19418038]
  [0.19981773 0.6006658 ]
  [0.97427017 0.0743025 ]
  [0.06394964 0.41665774]]

 [[0.35400214 0.70511692]
  [0.10454048 0.30578514]
  [0.56111413 0.60419269]
  [0.60252381 0.99284728]]]

Shape: (3, 4, 2)
Número de dimensões: 3
Número total de elementos: 24
Tipo dos dados: float64
Tamanho de cada elemento (bytes): 8
Tamanho total (bytes): 192


## 4. Indexação e Slicing Avançado

### 4.1 Teoria: Modelo de Indexação NumPy

NumPy oferece vários métodos de indexação:
1. **Indexação básica**: Similar a listas Python
2. **Indexação booleana**: Seleção usando máscaras booleanas
3. **Indexação fancy**: Usando arrays de índices
4. **Slicing**: Acesso a subarrays com step e intervalos

In [4]:
# Criando array de exemplo
arr = np.arange(1, 26).reshape(5, 5)
print("Array original:\n", arr)

# Indexação básica
print("\nElemento na linha 1, coluna 2:", arr[1, 2])
print("Última linha:\n", arr[-1])

# Slicing
print("\nLinhas 1 a 3, colunas 2 a 4:\n", arr[1:4, 2:5])
print("Todos os elementos com step 2:\n", arr[::2, ::2])

# Indexação booleana
mask = arr > 20
print("\nMáscara booleana:\n", mask)
print("Elementos > 20:", arr[mask])

# Indexação fancy
print("\nSelecionando linhas 0 e 4, colunas 1 e 3:\n", arr[[0, 4], [1, 3]])

Array original:
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]

Elemento na linha 1, coluna 2: 8
Última linha:
 [21 22 23 24 25]

Linhas 1 a 3, colunas 2 a 4:
 [[ 8  9 10]
 [13 14 15]
 [18 19 20]]
Todos os elementos com step 2:
 [[ 1  3  5]
 [11 13 15]
 [21 23 25]]

Máscara booleana:
 [[False False False False False]
 [False False False False False]
 [False False False False False]
 [False False False False False]
 [ True  True  True  True  True]]
Elementos > 20: [21 22 23 24 25]

Selecionando linhas 0 e 4, colunas 1 e 3:
 [ 2 24]


## Exercício 1: Manipulação de Arrays

1. Crie um array 8x8 com valores aleatórios entre 10 e 50
2. Selecione apenas os valores pares
3. Extraia a submatriz central 4x4
4. Inverta as linhas do array

In [5]:
# 1. Criando array
random_matrix = np.random.randint(10, 50, size=(8, 8))
print("Array original:\n", random_matrix)

# 2. Valores pares
pares = random_matrix[random_matrix % 2 == 0]
print("\nValores pares:\n", pares)

# 3. Submatriz central
central = random_matrix[2:6, 2:6]
print("\nSubmatriz central:\n", central)

# 4. Invertendo linhas
inverted = random_matrix[::-1]
print("\nArray com linhas invertidas:\n", inverted)

Array original:
 [[45 18 33 11 14 46 49 34]
 [21 16 45 17 11 19 36 46]
 [25 36 42 26 10 47 29 33]
 [11 35 21 21 22 44 28 15]
 [37 42 16 36 34 38 23 35]
 [18 23 20 28 17 22 23 14]
 [12 38 14 28 32 41 42 28]
 [30 14 13 47 24 27 12 11]]

Valores pares:
 [18 14 46 34 16 36 46 36 42 26 10 22 44 28 42 16 36 34 38 18 20 28 22 14
 12 38 14 28 32 42 28 30 14 24 12]

Submatriz central:
 [[42 26 10 47]
 [21 21 22 44]
 [16 36 34 38]
 [20 28 17 22]]

Array com linhas invertidas:
 [[30 14 13 47 24 27 12 11]
 [12 38 14 28 32 41 42 28]
 [18 23 20 28 17 22 23 14]
 [37 42 16 36 34 38 23 35]
 [11 35 21 21 22 44 28 15]
 [25 36 42 26 10 47 29 33]
 [21 16 45 17 11 19 36 46]
 [45 18 33 11 14 46 49 34]]


## 5. Operações Matemáticas e Broadcasting

### 5.1 Teoria: Broadcasting

O broadcasting é um conjunto de regras que permite operações entre arrays de diferentes shapes:

**Regras:**
1. Dimensões são comparadas a partir da direita
2. Dois eixos são compatíveis se:
   - São iguais, ou
   - Um deles é 1
3. Arrays com menos dimensões têm '1' preposto ao seu shape

In [6]:
# Exemplos de broadcasting

# Array 3x3
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Array 1x3
b = np.array([10, 20, 30])

# Operação com broadcasting
result = a + b
print("Resultado do broadcasting:\n", result)

# Exemplo complexo
arr1 = np.ones((5, 1, 4))
arr2 = np.ones((3, 4))
print("\nShape do resultado:", (arr1 + arr2).shape)

Resultado do broadcasting:
 [[11 22 33]
 [14 25 36]
 [17 28 39]]

Shape do resultado: (5, 3, 4)


### 5.2 Operações Matemáticas Básicas

In [7]:
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])

print("Adição:", x + y)  # ou np.add(x, y)
print("Subtração:", x - y)
print("Multiplicação:", x * y)  # Element-wise, não multiplicação matricial
print("Divisão:", y / x)
print("Potenciação:", x ** 2)
print("Produto escalar:", np.dot(x, y))

# Funções matemáticas
print("\nSeno:", np.sin(x))
print("Exponencial:", np.exp(x))
print("Logaritmo:", np.log(x))

Adição: [5 7 9]
Subtração: [-3 -3 -3]
Multiplicação: [ 4 10 18]
Divisão: [4.  2.5 2. ]
Potenciação: [1 4 9]
Produto escalar: 32

Seno: [0.84147098 0.90929743 0.14112001]
Exponencial: [ 2.71828183  7.3890561  20.08553692]
Logaritmo: [0.         0.69314718 1.09861229]


## Exercício 2: Cálculo Matricial

1. Crie uma matriz 4x4 com valores de 1 a 16
2. Calcule:
   - A soma de todos os elementos
   - A média de cada coluna
   - O produto matricial consigo mesma
   - O determinante
3. Normalize a matriz (valores entre 0 e 1)

In [8]:
# Solução do Exercício 2

# 1. Criando matriz
mat = np.arange(1, 17).reshape(4, 4)
print("Matriz original:\n", mat)

# 2. Cálculos
print("\nSoma total:", mat.sum())
print("Média das colunas:", mat.mean(axis=0))
print("\nProduto matricial:\n", np.matmul(mat, mat))
print("\nDeterminante:", np.linalg.det(mat))

# 3. Normalização
mat_norm = (mat - mat.min()) / (mat.max() - mat.min())
print("\nMatriz normalizada:\n", mat_norm)

Matriz original:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

Soma total: 136
Média das colunas: [ 7.  8.  9. 10.]

Produto matricial:
 [[ 90 100 110 120]
 [202 228 254 280]
 [314 356 398 440]
 [426 484 542 600]]

Determinante: 0.0

Matriz normalizada:
 [[0.         0.06666667 0.13333333 0.2       ]
 [0.26666667 0.33333333 0.4        0.46666667]
 [0.53333333 0.6        0.66666667 0.73333333]
 [0.8        0.86666667 0.93333333 1.        ]]


## 6. Álgebra Linear com NumPy

### 6.1 Teoria: Submódulo linalg

O NumPy fornece o submódulo `numpy.linalg` com funções para:
- Decomposições matriciais (LU, QR, SVD)
- Solução de sistemas lineares
- Cálculo de autovalores e autovetores
- Normas matriciais

In [9]:
# Exemplos de álgebra linear

# Sistema linear: 3x + y = 9, x + 2y = 8
A = np.array([[3, 1], [1, 2]])
b = np.array([9, 8])

# Resolvendo o sistema
x = np.linalg.solve(A, b)
print("Solução do sistema:", x)

# Autovalores e autovetores
eigenvalues, eigenvectors = np.linalg.eig(A)
print("\nAutovalores:", eigenvalues)
print("Autovetores:\n", eigenvectors)

# Decomposição SVD
U, S, Vt = np.linalg.svd(A)
print("\nDecomposição SVD:")
print("U:\n", U)
print("S (valores singulares):", S)
print("Vt:\n", Vt)

Solução do sistema: [2. 3.]

Autovalores: [3.61803399 1.38196601]
Autovetores:
 [[ 0.85065081 -0.52573111]
 [ 0.52573111  0.85065081]]

Decomposição SVD:
U:
 [[-0.85065081 -0.52573111]
 [-0.52573111  0.85065081]]
S (valores singulares): [3.61803399 1.38196601]
Vt:
 [[-0.85065081 -0.52573111]
 [-0.52573111  0.85065081]]


## 7. Otimização de Performance

### 7.1 Teoria: Vetorização vs Loops

NumPy é otimizado para operações vetorizadas. Operações com loops Python são geralmente mais lentas.

In [10]:
# Comparação de performance
large_arr = np.random.rand(1000000)

def sum_with_loop(arr):
    total = 0
    for num in arr:
        total += num
    return total

# Medindo tempo
loop_time = timeit('sum_with_loop(large_arr)', globals=globals(), number=10)
numpy_time = timeit('np.sum(large_arr)', globals=globals(), number=10)

print(f"Tempo com loop Python: {loop_time:.4f} segundos")
print(f"Tempo com NumPy: {numpy_time:.6f} segundos")
print(f"NumPy foi {loop_time/numpy_time:.0f}x mais rápido")

Tempo com loop Python: 0.6412 segundos
Tempo com NumPy: 0.004188 segundos
NumPy foi 153x mais rápido


### 7.2 Técnicas de Otimização

1. **Evitar loops Python**: Usar operações vetorizadas sempre que possível
2. **Views vs cópias**: Operações de slicing retornam views (sem cópia)
3. **Pré-alocação**: Criar arrays de destino antes das operações
4. **Tipos de dados**: Usar dtype apropriado para economizar memória

In [11]:
# Exemplo: Pré-alocação vs concatenação

def slow_append(size):
    result = np.array([])
    for i in range(size):
        result = np.append(result, i)
    return result

def fast_preallocate(size):
    result = np.empty(size)
    for i in range(size):
        result[i] = i
    return result

# Comparação
size = 10000
slow_time = timeit('slow_append(size)', globals=globals(), number=10)
fast_time = timeit('fast_preallocate(size)', globals=globals(), number=10)

print(f"Tempo com append: {slow_time:.4f} segundos")
print(f"Tempo com pré-alocação: {fast_time:.6f} segundos")
print(f"Pré-alocação foi {slow_time/fast_time:.0f}x mais rápida")

Tempo com append: 0.3277 segundos
Tempo com pré-alocação: 0.006799 segundos
Pré-alocação foi 48x mais rápida
