## 3. Criando Arrays NumPy

### 3.1 Métodos Básicos de Criação

In [2]:
import numpy as np

from Terceiro_Semestre_Ciencia_de_Dados.MADA.explicação import identity

In [3]:
array1d = np.array([10, 15,14])
print(array1d)

[10 15 14]


In [4]:
array2d = np.array([[15, 10, 18, 16], [19, 25, 30, 80]])
print(array2d)

[[15 10 18 16]
 [19 25 30 80]]


In [7]:
zeros = np.zeros((3, 3))
print(zeros)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [9]:
ones = np.ones((5, 5))
print(ones)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [12]:
full = np.full(10, 8)
print(full)

[8 8 8 8 8 8 8 8 8 8]


In [13]:
identity = np.identity(5)
print(identity)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [16]:
range_arr = np.arange(0, 16, 2 )
print(range_arr)

[ 0  2  4  6  8 10 12 14]


In [19]:
random_a = np.random.rand(5)
print(random_a)

[0.24454818 0.77629799 0.16366337 0.13357349 0.46552552]


In [32]:
arr = np.random.rand(3,4,2)

print(arr)

[[[0.2957873  0.22691707]
  [0.4864434  0.53066786]
  [0.09706843 0.87086247]
  [0.73808557 0.75302591]]

 [[0.47649308 0.27395734]
  [0.28317304 0.751968  ]
  [0.57811912 0.16404828]
  [0.72307724 0.28942198]]

 [[0.65847616 0.23637865]
  [0.96333835 0.43405827]
  [0.73263948 0.33804446]
  [0.86465849 0.34786656]]]


In [31]:
print(arr.shape)

(3, 4, 2)


In [30]:
ndim = arr.ndim
print(ndim)

3


In [29]:
print(arr.size)

24


In [26]:
print(arr.dtype)

float64


In [27]:
print(arr.itemsize)

8


In [28]:
print(arr.nbytes)

192
