## 3. Criando Arrays NumPy

### 3.1 Métodos Básicos de Criação

Um array é uma estrutura de dados que armazena vários valores em uma única variável,

podendo armazenar valores numéricos, listas de nomes, produtos, funcionários.






Um array NumPy é uma estrutura que guarda vários números juntos,

organizados de um jeito que facilita fazer contas e operações matemáticas.

Ele funciona como uma "super lista" que pode ser manipulada de forma muito rápida!

In [2]:
import numpy as np

In [3]:
# Criando um array a partir de uma lista do Python (1D - uma dimensão)

array1d = np.array([1, 2, 3, 4, 5]) # Esse é um array simples, como uma fileira com valores  unidimensional.
print("1D array:", array1)

NameError: name 'array1' is not defined

In [5]:
# Criando um array bidimensional (2D) a partir de uma lista de listas
array2d = np.array([[1, 2, 3], [4, 5, 6]])  # Aqui, temos números organizados em linhas e colunas, como uma tabela do Excel!
print("\n2D array:\n", array2d )  # Exibe a matriz 2D (com linhas e colunas)


2D array:
 [[1 2 3]
 [4 5 6]]


# Criando arrays especiais com NumPy

In [21]:

zeros = np.zeros((5, 4)) # Criando um array de zeros com 5 linhas e 4 colunas
print(f'''Zeros
{zeros} ''')  # Exibe a matriz 3x4 preenchida com zeros

Zeros
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]] 


In [31]:
# Criando um array tridimensional (3D) preenchido com uns, de tamanho 2x2x2
ones = np.ones((3, 3, 3))
print("\nOnes 3D:\n", ones)  # Exibe o array 3D preenchido com uns


Ones 3D:
 [[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]]


In [5]:
# Também podemos criar um aray com valores específicos.
# O primeiro parâmetro  representa o tamanho do array (quantos elementos ele terá).
#  segundo parâmetro é o valor que será preenchido em todos os elementos.

a = np.full(10, 3)
print(a)

[3 3 3 3 3 3 3 3 3 3]


In [23]:
# Criando uma matriz identidade de tamanho 3x3 (diagonal principal com 1s)
identity = np.eye(3)
print("\nMatriz identidade:\n", identity)  # Exibe a matriz identidade 3x3


Matriz identidade:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [9]:
# Criando um array com valores sequenciais de 0 a 18, com passo de 2
range_arr = np.arange(0, 20, 2)  # Funciona como a função range(), mas retorna um array NumPy
print("\nArray com arange:\n", range_arr)  # Exibe os números pares de 0 a 18


Array com arange:
 [ 0  2  4  6  8 10 12 14 16 18]


In [10]:
# Criando um array com 5 números aleatórios entre 0 e 1
random_arr = np.random.rand(5)
print("\nArray aleatório:\n", random_arr)  # Exibe um array de 5 números aleatórios


Array aleatório:
 [0.25898253 0.63117184 0.70413183 0.29983043 0.78659851]
